# For local testing

version: "3"
services:

  mongo:
    image: mongo:2.6
    command: mongod --smallfiles --logpath=/dev/null
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - ./local_db/:/data/db/
    ports:
      - 27018:27017
  jumpseat:
    build:
      context: "."
    environment:
      JUMP_ENV: development
    volumes:
      - ./local_config/config/:/var/www/html/application/config/
      - ./local_config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 3000:80
    depends_on:
      - mongo